string:
  base62:
    abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
  originUrl:
    loooooongggggurl
  shortUrl:
    aab
  base62matchPattern:
    ^([A-Za-z0-9]*)$
---

#url 디비
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.101.162.240:3306/chop?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: short
    password: nexters12

    jpa:
        show-sql : true
        database : default
        profiles:
          hibernate:
            format_sql : true

    dbcp2:
      validation-query: select 1
      test-while-idle: true
      time-between-eviction-runs-millis: 30000


---
#jpa 설정

jpa:
  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    org.hibernate.sql : debug
    org.hibernate.type.descriptor.sql : TRACE