string:
  base62:
    abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
  originUrl:
    loooooongggggurl
  shortUrl:
    aab
  base62matchPattern:
    ^([A-Za-z0-9]*)$
---

#url 디비
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://101.101.162.240:3306/chop?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: short
    password: nexters12

    jpa:
        show-sql : true
        database : default
        profiles:
          hibernate:
            format_sql : true
---
#statistics 디비
bar :
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://statistics-bd.ci6m5mpn73xb.ap-northeast-2.rds.amazonaws.com:3306/statistics?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: nexters
    password: nexters12

---
#jpa 설정

jpa:
  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    org.hibernate.sql : debug
    org.hibernate.type.descriptor.sql : TRACE